---
ropsten-goerli:
  children:
    oracle:
      hosts:
        ec2-18-224-173-5.us-east-2.compute.amazonaws.com:
          ansible_user: ubuntu
          ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY: "a4f88cb1691864893fc45b0e8f5918760a1b14deb95fd10c5fe4c662e4828f41"
          #syslog_server_port: "<protocol>://<ip>:<port>" # When this parameter is set all bridge logs will be redirected to <ip>:<port> address.